apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ytdl-material
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10G"
spec:
  ingressClassName: nginx
  rules:
    - host: ytdl.cuidaapp.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ytdl-material
                port:
                  number: 80
